# Generated by Django 5.2.6 on 2025-09-16 18:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('jerseys', 'Jerseys'), ('footwear', 'Footwear'), ('training', 'Training Gear'), ('accessories', 'Accessories'), ('equipment', 'Equipment'), ('fan_collection', 'Fan Collection'), ('kids', 'Kids Collection'), ('goalkeeper', 'Goalkeeper Gear'), ('retro', 'Retro & Vintage'), ('custom', 'Customization')], default='custom', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
