# Generated by Django 5.2.6 on 2025-09-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_decription_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jerseys', 'Jerseys'), ('footwear', 'Footwear'), ('training', 'Training Gear'), ('accessories', 'Accessories'), ('equipment', 'Equipment'), ('fan_collection', 'Fan Collection'), ('kids', 'Kids Collection'), ('goalkeeper', 'Goalkeeper Gear'), ('retro', 'Retro & Vintage'), ('custom', 'Customization')], default='custom', max_length=20),
        ),
    ]
